
products = [
    {"name":"rice", "Category":"Food", "Quantity":348, "product_id":"1"},
    {"name":"sunglasses", "Category":"Fashion", "Quantity":324, "product_id":"2"},
    {"name":"milkshake", "Category":"Drinks", "Quantity":431, "product_id":"3"},
    {"name":"scarf", "Category":"Clothing", "Quantity":312, "product_id":"4"},
    {"name":"cakes", "Category":"Food", "Quantity":234, "product_id":"5"},
    {"name":"beans", "Category":"Food", "Quantity":343, "product_id":"6"},
    {"name":"coffee", "Category":"Drinks", "Quantity":312, "product_id":"7"},
    {"name":"sportshoes", "Category":"Sportswear", "Quantity":214,"product_id":"8"},
    {"name":"soda", "Category":"Drinks", "Quantity":341,"product_id":"9"},
    {"name":"shirt", "Category":"Clothing", "Quantity":112, "product_id":"10"},
    {"name":"socks", "Category":"Clothing", "Quantity":123, "product_id":"11"},
    {"name":"shoes", "Category":"Clothing", "Quantity":345, "product_id":"12"},
    {"name":"t-shirt", "Category":"Clothing", "Quantity":567,"product_id":"13"},
    {"name":"glasses", "Category":"Fashion", "Quantity":987, "product_id":"14"},
    {"name":"watch", "Category":"Fashion", "Quantity":230,   "product_id":"15"},
    {"name":"bag", "Category":"Fashion", "Quantity":578, "product_id":16},
    {"name":"shorts", "Category":"Clothing", "Quantity":345, "product_id":"17"},
    {"name":"jacket", "Category":"Clothing", "Quantity":890, "product_id":"18"},
    {"name":"jeans", "Category":"Clothing", "Quantity":345,  "product_id":"19"},
    {"name":"towel", "Category":"Clothing", "Quantity":290,  "product_id":"20"},
    {"name":"sandals", "Category":"Clothing", "Quantity":799,"product_id":"21"},
    {"name":"t-shirt", "Category":"Clothing", "Quantity":954,"product_id":"22"},
    {"name":"watch", "Category":"Fashion", "Quantity":434,   "product_id":"25"},
    {"name":"bag", "Category":"Fashion", "Quantity":123, "product_id":"26"},
    {"name":"shorts", "Category":"Clothing", "Quantity":456, "product_id":"27"},
    {"name":"jacket", "Category":"Clothing", "Quantity":980, "product_id":"28"},
]
